<?php

require_once __DIR__ . '/.env.php';
$apiKey = RAZORPAY_KEY;

?>

<script src="https://code.jquery.com/jquery-3.5.0.js"></script>




<form action="success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_nchCwzf6fwMAUI" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_POST['amt'] * 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image=""
    data-prefill.name="<?php echo htmlspecialchars($_POST['name'], ENT_QUOTES, 'UTF-8');?>"
    data-prefill.email="<?php echo htmlspecialchars($_POST['email'], ENT_QUOTES, 'UTF-8');?>"
    data-prefill.contact="<?php echo htmlspecialchars($_POST['mobile'], ENT_QUOTES, 'UTF-8');?>"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>